### ISSUE TITLE
Persistant wakelock despite polling interval selected

### ISSUE THREAD

**Issue by Tryptamine9** [LeanderBB/you-have-mail#23]
Hello. I have noticed that despite the polling interval selected, there is a permanent wakelock placed on the CPU when this app is active. It would be fantastic if the application only woke the CPU when needed at the polling time selected instead of permanently running the processor and draining the battery. 

Otherwise an absolutly fantastic and neccisairy application, since all other Proton apps work just fine sans Google Play Services (even Proton Calendar)!

**Comment by LeanderBB** [comment]
Hey @Tryptamine9, thanks for the feedback.

I'm aware of the situation. Unfortunately, as far as I could understand, keeping that wakelock is required for foreground services so they actually run correctly.

I'm in the middle of some internal changes so that I can eventually migrate to Android's Work Manager, which should, in theory, seamlessly handle this case.

I'll post some updates here once I get to that point.
