### ISSUE TITLE
[Feature Request] SOCKS5 Proxy Support

### ISSUE THREAD

**Issue by kalekad** [LeanderBB/you-have-mail#3]

**Comment by LeanderBB** [comment]
Hey @kalekad, I need a bit more information about the use case for this feature. 

Are you using the Rust crates or the Android application? If the latter, does setting a proxy through the Android settings work for you?

**Comment by LeanderBB** [comment]
Interesting setup, thanks for the suggestion!

I did a quick check on the libraries currently in use and it seems doable to add socks5 support. It may take a bit longer as I didn't consider proxy support in the original architecture :sweat_smile:.  

Once I'm finished with my current activity, I'll start working on this next (provided life doesn't get in the way :))

**Comment by LeanderBB** [comment]
@kalekad  I have added Proxy support for HTTPS and SOCKS5 in https://github.com/LeanderBB/you-have-mail/releases/tag/v0.3.0. 

Please let me know if this works for you. I tested the connections against some python libraries and as far as I can tell everything seems to work.

However, I  have no "real world" SOCKS5 setup with which I can test this. Would be grateful if you could share your feedback :).

**Comment by LeanderBB** [comment]
It is hard to say what may be going wrong. I didn't want to spam notifications for disconnected/connected to not get annoyed during network issues. I could look into adding an option for that :thinking: 

What I did notice is the status in the `Account Details` screen doesn't update properly at the moment, but the general account list should display the correct status.

Do you think you could share the logs? There maybe some more information there that might help diagnose the problem.

**Comment by LeanderBB** [comment]
In the logs I can see:
```
 observer: Account Error: [redacted] => dev.lbeernaert.youhavemail.ServiceException$Unknown: msg=An error occurred preparing the request
 ```
 
 Did you happen to get an error notification for this? 
 
 I'm not sure what may have caused this, I will try to get a new build out with more information surrounding this error.

**Comment by LeanderBB** [comment]
If you update to v0.3.1 we should have more details about why the request is failing.

**Comment by LeanderBB** [comment]
Can you give me the logs for this run?

-------- Original Message --------
On Mar 24, 2023, 11:19, kalekad < ***@***.***> wrote:
After updating to 0.3.1 I got this.
￼
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were assigned.￼Message ID: ***@***.***>
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[https://github.com](<a href=)/LeanderBB/you-have-mail/issues/3#issuecomment-1482566637">https://github.com/LeanderBB/you-have-mail/issues/3#issuecomment-1482566637", "url": "[https://github.com](<a href=)/LeanderBB/you-have-mail/issues/3#issuecomment-1482566637">https://github.com/LeanderBB/you-have-mail/issues/3#issuecomment-1482566637", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by LeanderBB** [comment]
Ok. I will need to spend some time to dig deeper into this, but it seems that is related to a network transmission issue such as the connection being lost halfway through the transmission of data.

I will close this issue as the feature itself is complete.  I will open a new issue to track improvements for the network transmission.

**Comment by LeanderBB** [comment]
You can follow the progress with #4
