### ISSUE TITLE
Allow deleting permanent notification on Android 13

### ISSUE THREAD

**Issue by m0byn** [LeanderBB/you-have-mail#44]
Hello,
on my tablet running android 13 I am not able to delete the permanent notification of You Have Mail Background Service Running. In my opinion, it is rather annoying having a permanent notification. It would be nice if you could allow deleting the notification on android 13 as well.

**Comment by LeanderBB** [comment]
Hey, unfortunately this is enforced by Android. 

The app in its current state uses a background process to poll the servers. In order to create a background process we are required to display a notification.

I have some plans to move away from the background process, but for the moment there is nothing I can do.

**Comment by m0byn** [comment]
Hm...interesting. I was reporting it as a different app I use, which also uses background services, actually allows removing this notification. I don't know what they are doing different...

**Comment by licaon-kter** [comment]
You can't hide it via the notification settings?

**Comment by LeanderBB** [comment]
A small update based on #42, I will move the polling mechanism to a worker job, so in the future the icon will only appear once the background worker is polling and should vanish afterwards.

**Comment by LeanderBB** [comment]
The [0.16.0](https://github.com/LeanderBB/you-have-mail/releases/tag/v0.16.0) no longer displays any permanent notification icon.
